### ISSUE TITLE
Summoned Allies disappear from the game state

### ISSUE THREAD

**Issue by ronderksen** [Lurkars/gloomhavensecretariat#301] opened 2023-05-19 14:59 UTC
When I have multiple summons out with my Boneshaper, they have a habit of disappearing in the app at some point. Only one remains visible. Adding them back only works temporarily.

**Comment by Lurkars** [comment] 2023-05-19 16:08
Can your please first verify if all clients and server are on the latest version.

**Comment by keinkurt** [comment] 2023-05-21 19:58
We have another wired bug, that sometimes a summoned and killed skeleton appears in later rounds and we have to kill it again (drain the HP to 0) and then it's appear again one round later and so on. Do you know why this can happen. Every time we use the latest server and client version, but both self hosted. The last version we played was Client v0.64.3 and Server v0.64.0.

**Comment by Lurkars** [comment] 2023-05-22 13:58
Can help a lot, if you can provide me your Game states and more infos. With only 2 clients connected, I am not able to reproduce this after my fixes in >= v0.64.0

**Comment by keinkurt** [comment] 2023-05-31 09:02
In our last session, we also can't reproduce this behaviour. For me you can close this issue.

**Comment by Lurkars** [comment] 2023-05-31 09:04
Yes, I think only one outdated client can produce many errors on this. So @ronderksen please check your clients and if you can't reproduce anymore with all on latest version, then close this issue please.

**Comment by ronderksen** [comment] 2023-06-03 09:27
I've updated the server and client to the latest version. Will see if it's fixed when we play on Monday!

**Comment by ronderksen** [comment] 2023-06-05 20:45
Works perfectly now

**Closed** 2023-06-05 20:46 UTC
Labels: pending
