### ISSUE TITLE
Can't create new game codes

### ISSUE THREAD

**Issue by BrianJW81** [Lurkars/gloomhavensecretariat#324] opened 2023-06-17 06:07 UTC
No matter what I do, when I specify settings and save it with a game code the login isn't created.  I'm on 0.66.7.  I do have a total of 16 login's at the moment do to my learning how to properly configure things.

**Comment by Lurkars** [comment] 2023-06-17 06:25
Can you click the feedback menu, export a data dump and send it to me? Possible bug in settings sync that only appears on specific settings.

**Comment by BrianJW81** [comment] 2023-06-17 14:36
it won't let me upload the file here so here's a google drive link: https://drive.google.com/file/d/19CIF6SWnlv8qrn6IXoUf92FbtqoQBs7h/view?usp=drive_link

**Comment by Lurkars** [comment] 2023-06-19 06:17
You are using your own server? Is it on latest version? (you can delete your dump if you want to, I stored the file, in future you can just send it via email to support@gloomhaven-secretariat.de)

**Comment by BrianJW81** [comment] 2023-06-30 23:59
sorry, missed this.  This is a server I run on my local box.  It was working fine for weeks, I was creating codes without issue.  Then one day I updated the client and noticed it was behaving strangely (couldn't create a new code and couldn't get draw to work)

**Comment by BrianJW81** [comment] 2023-07-01 00:12
I will also add, whenever I click next round/draw I see this in the JS console:

[GHS] Error: Permission(s) missing

**Comment by Lurkars** [comment] 2023-07-01 04:39
Really strange, can you first try updating all (client and server) to latest version. If it's still happening, can you try to send me your local `.ghs` folder via email? Have you tried accessing from a clean browser?

**Comment by BrianJW81** [comment] 2023-07-02 15:53
where is that folder located?  I've installed latest server/client and it still happens.  This also happens on window browsers, iphones, and android devices

**Comment by Lurkars** [comment] 2023-07-02 16:18
See last paragraph of https://github.com/Lurkars/ghs-server#installation--running

It's located in your home folder (https://en.m.wikipedia.org/wiki/Home_directory#Default_home_directory_per_operating_system)

**Comment by Lurkars** [comment] 2023-07-03 13:37
> To create new game codes, you need to enable `public` server setting. https://github.com/Lurkars/ghs-server#running-public (it has nothing to do with public exposed, more that everyone can create new games)

I see you didn't touch your application.properties. So I think the issue is very easy solvable by just following the linked description. But anyway I reference for you here:
Since you already located your `.ghs`-folder, open the `application.properties` file with a simple editor and add the line `ghs-server.public=true`. Restart the server, afterwards, creating new game codes should work fine.

For the Round update, I was able to identify an issue in the server permissions model, so I will fix this.

**Comment by BrianJW81** [comment] 2023-07-03 14:29
Thanks, I’ll do that. I’m just confused why this started happening. I had like 10 codes already created before I hit this issue. Was this property a recent change?Sent from my iPhoneOn Jul 3, 2023, at 6:37 AM, Lurkars ***@***.***> wrote:﻿

To create new game codes, you need to enable public server setting. https://github.com/Lurkars/ghs-server#running-public (it has nothing to do with public exposed, more that everyone can create new games)

I see you didn't touch your application.properties. So I think the issue is very easy solvable by just following the linked description. But anyway I reference for you here:
Since you already located your .ghs-folder, open the application.properties file with a simple editor and add the line ghs-server.public=true. Restart the server, afterwards, creating new game codes should work fine.
For the Round update, I was able to identify an issue in the server permissions model, so I will fix this.

**Comment by Lurkars** [comment] 2023-07-03 14:32
> I had like 10 codes already created before I hit this issue. Was this property a recent change?

You didn't create new games, you added permissions to the one existing game. This is a difference, there has nothing changed regarding this!

**Comment by Lurkars** [comment] 2023-07-03 18:13
So I hopefully fixed the issue in [ghs-server v0.67.6](https://github.com/Lurkars/ghs-server/releases/tag/v0.67.6). There are also some improvements for permissions in new [client v0.67.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.6). So also update to latest version there. 

Hope it works out and if so, please close this issue, thanks!

**Closed** 2023-07-03 22:48 UTC
Labels: to test
