### ISSUE TITLE
Frosthaven party sheet missing

### ISSUE THREAD

**Issue by ericvoshall** [Lurkars/gloomhavensecretariat#107] opened 2023-02-03 05:09 UTC
Hi, we were testing out Gloomhaven Secretary for a new Frosthaven campaign and noticed the party sheet is the Gloomhaven one not the Frosthaven one - any plans to update?

**Comment by Lurkars** [comment] 2023-02-03 05:26
Yes, it will come definitely. Have to check how much it will take to add it, so no concrete ETA by now, but I am talking about next days or next weeks...

**Comment by Lurkars** [comment] 2023-02-03 19:44
> Semi-related, but are there any bugs or features I would be able to submit a PR for to help out on for this project?

Thanks for providing help. I do not have special roadmaps to delegate some work. In general the most lacking thing is just the boring data, which is not really development. But if you have time, take a look at Frosthaven Scenarios missing the room/rules data and just try to provide it.

To topic: I started preparation for the FH sheet. So will hopefully not take too long.

**Comment by Lurkars** [comment] 2023-02-11 15:42
![Current Frosthaven Campaign Sheet](https://user-images.githubusercontent.com/2760570/218267200-8327e650-3d1f-4601-8385-a1ef4dd79566.png)

Will be published today or tomorrow. Will need some proper testing and feedback, because I only know all this stuff from the rule book (Don't own FH yet), so maybe some stuff will be not completely correct to track.

But yes, it's ready, just need some fine tuning and currently I am working on the mechanic to move character resources (from the character sheet) to FH supply!

**Comment by Lurkars** [comment] 2023-02-11 17:53
By the way: will it be useful to implement the town guard deck? I know nothing about all those mechanics yet. So selecting perks currently has no effect!

**Comment by Lurkars** [comment] 2023-02-11 20:18
Implemented now with [v0.45.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.45.0). Please test and give feedback if everything is working as expected. Some Infos:
- because I still like the old campaign view for seeing scenarios, prosperity and donations, the sheet is still flippable as before with this view, so the prosperity and retirements are not on the initial sheet, click on the title "Campaign Sheet" to change dialog
- Retirements now implemented (for all edition), so if you mark a chars personal quest as done, char will retire and added to the retirements list
- stickers can be add by just typing the title in (as in screenshot: "friends of the icespeakers" or "Friend of the Icespeakers" would all work to add the sticker there, if text is unknown, the entered text will be added instead of sticker, so no validation (because I also don't know if all stickers are correct, if there's more etc)
- to move resources from a char to Frosthaven supply, use the character's sheet, where a "Move to Frosthaven supply" button is located on Resources  to open menu to move resources
- I forgot to add many of the undo-texts, so currently many changes will show as placeholder label in undo menu, will be fixed

**Comment by Lurkars** [comment] 2023-02-11 20:38
> Awesome, thank you! I will test this out. Does the calendar on the FH sheet support adding section numbers to the days?

As mentioned, I only know basics from rulebook. So honestly I don't know what you mean, or better: that this should be possible. So please just test it and collect all things missing/wrong and give feedback here. Then I can try to implement/fix stuff.

**Comment by UChess1986** [comment] 2023-02-11 20:41
> By the way: will it be useful to implement the town guard deck? I know nothing about all those mechanics yet. So selecting perks currently has no effect!

Yes, that would be very useful!

For additional feedback, it would be cool if after the party goes back to frosthaven a new checkmark gets added automatically on the season part of the campaign sheet.

**Comment by Lurkars** [comment] 2023-02-13 13:48
> Awesome, thank you! I will test this out. Does the calendar on the FH sheet support adding section numbers to the days?

Just added this functionality now by double click (long press on mobile) on a week!

**Comment by Doctawin** [comment] 2023-02-14 00:14
The campaign sheet looks awesome. It works fine on a computer, but some of the fields (supply values, inspiration, defense) aren't displaying correctly on an iPad:
![Screenshot 2023-02-12 at 7 51 57 AM](https://user-images.githubusercontent.com/121493484/218604738-12a28f88-3684-474f-bf25-6b24ecac189b.png)

**Comment by Lurkars** [comment] 2023-02-14 18:59
I changed font-size and hope that fixes the IPad issue. I cannot test myself sadly. If you're able to debug the browser session on Ipad, I am pretty sure it is bound to font-size!

**Comment by UChess1986** [comment] 2023-02-14 19:17
> I changed font-size and hope that fixes the IPad issue. I cannot test myself sadly. If you're able to debug the browser session on Ipad, I am pretty sure it is bound to font-size!

I just tested on Iphone it looks *better*

![image](https://user-images.githubusercontent.com/104481784/218835389-1b9120b7-9d96-4871-92de-53757e549f85.png)

**Comment by Lurkars** [comment] 2023-02-14 19:27
> I just tested on Iphone it looks *better*

But still not fitting... Will try to increase height of element in next iteration

**Comment by Doctawin** [comment] 2023-02-14 20:13
> > I just tested on Iphone it looks _better_
> 
> But still not fitting... Will try to increase height of element in next iteration

I can confirm that it looks better on iPad. The inspiration and defense values fully show now, but there's not enough vertical space for the supply values. So, it looks similar to the above screenshot.

**Comment by Lurkars** [comment] 2023-02-15 20:59
So in [v0.45.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.45.5) I now increased the size of the input field. As sad, sadly I cannot test on Apple devices, so I hope it looks better now.

The "campaign sticker" area is now smaller on purpose, because the Town Guard Deck will move next to it in future!

**Comment by UChess1986** [comment] 2023-02-15 21:09
Its looking great! Tested on iphone

**Comment by Doctawin** [comment] 2023-02-15 22:46
Also looks great on iPad. Thanks!

**Comment by Lurkars** [comment] 2023-02-16 09:59
So besides Town Guard Deck (which isn't really part of the campaign sheet), are there any features missing/issues with current feature? Otherwise please close this issue @ericvoshall if it is solved for you this way now.

**Comment by UChess1986** [comment] 2023-02-16 16:05
> So besides Town Guard Deck (which isn't really part of the campaign sheet), are there any features missing/issues with current feature? Otherwise please close this issue @ericvoshall if it is solved for you this way now.

It looks pretty complete so far, for the retired characters we just use the notes section on the regular campaign sheet right?

**Comment by Lurkars** [comment] 2023-02-16 17:11
> - Retirements now implemented (for all edition), so if you mark a chars personal quest as done, char will retire and added to the retirements list

The retirement list is in the "backside", click on the title "campaign sheet" with the arrow on top to access it. Retirements only visible if you have one. To migrate existing sheet, just add character, fill out character sheet and mark personal quest as done! Then it should appear on retirement list!

**Comment by sahilthapar** [comment] 2023-04-03 17:33
> Awesome, thank you! I will test this out. Does the calendar on the FH sheet support adding section numbers to the days?

Just wanted to bring this up again with some clear details. I can create a new feature request for it if needed.

The calendar in Frosthaven is used to track the passage of time. (See attached image below) Each box denotes a week of time that has passed.
Some of the boxes come filled with Section Book numbers that the party has to read when they mark that box off. By default I believe these are every 5 scenarios (or weeks).

Over the course of the game, many events will ask you to add section numbers in those boxes to be read at a future time. It would be good, if we could "pencil in" (fill in) those boxes. So in essence, it changes the box from a simple toggle / checkbox to a text field that can also be checked off.

<img width="1105" alt="Screenshot 2023-04-03 at 10 25 49 AM" src="https://user-images.githubusercontent.com/3141362/229584277-52a05ed2-5c15-4ea5-8d2f-f666bf6af903.png">

**Comment by Lurkars** [comment] 2023-04-03 17:38
> > Awesome, thank you! I will test this out. Does the calendar on the FH sheet support adding section numbers to the days?
> 
> Just added this functionality now by double click (long press on mobile) on a week!

Adding sections to weeks is already implemented!

**Comment by sahilthapar** [comment] 2023-04-03 17:55
Thanks, somehow I missed that. Maybe scrolled past it too quickly.

**Comment by Lurkars** [comment] 2023-04-23 21:06
New additions to the sheet will be filed in new issues, so I will close this one now as complete.

**Closed by Lurkars** 2023-04-23 21:06 UTC
Labels: enhancement, to test, spoiler, pending

**Comment by Lurkars** [comment] 2023-05-31 08:39
Town Guard Deck is also added a few version ago (since [v0.65.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.4)). It's available on the campaign sheet as slider:


![Screenshot from 2023-05-23 21-33-05](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/3eb00d52-04dc-4190-91ee-5d92c2374e18)
![Screenshot from 2023-05-23 21-33-19](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/20546838-cf2f-44a4-b7e9-81acb075deea)

Perks are already supported. What's missing by now is as I see that some section/rewards or so also add cards to this, this is currently missing. Also keep in mind, that drawing is only possible when not playing a scenario. And maybe it need to be shuffled manually, haven't re-read the rules yet, how it completely works.
