### ISSUE TITLE
Frosthaven: Scenario 20 Bugs

### ISSUE THREAD

**Issue by sahilthapar** [Lurkars/gloomhavensecretariat#283] opened 2023-05-08 15:45 UTC
Some bugs in Scenario 20 (and perhaps general bugs as well)

Running Version: 0.63.0

[] There are two "a" and two "b" spawn points but the scenario only adds two monsters. One for "a" and one for "b". It should spawn ~four monsters instead~ one monster per active metal cabinet (objective) instead.
[] Major issues with objectives (Metal Cabinets) that keep getting replicated, we had to remove them at least 100 times over the 10-12 rounds. Same thing was happening with Boneshaper's summons as well. No matter how many times we killed them they would keep coming back.
[] Add a visual reminder to do trap damage to all characters and ruined machines at the start of each odd round except the first

**Comment by Lurkars** [comment] 2023-05-08 15:59
Thanks, I will check.

1. is clearly wrong, will be fixed,
3. Will also be added
4. Seems just wrong copied from flowshart, room also be fixed

For 3 I have no clue, cannot reproduce. Would be awesome if you still have this state or can reproduce it somehow if you can provide me a data dump via email (just use the `Feedback` button in main menu)

**Comment by sahilthapar** [comment] 2023-05-08 16:25
So for the objectives it was something like this,
We had 4 objectives marked 1-4. Every few seconds (perhaps on client connect / disconnect), a new one would be created with full health and same objective marker number, even if the original "Objective 1", let's say had already taken some damage.

A few quirky things that may or may not help.
- These "phantom clones" on death would not trigger the spawn a new monster dialog. However, the original one on death would. So somehow the app knows that there is a difference between these "phantom clones" and the original ones.
- Once the original objective was dead, the "phantom clones" no longer appeared for that particular objective marker number

The whole data was not really being reset, since other changes from same / other players were reflected during this time.

**Comment by Lurkars** [comment] 2023-05-08 16:39
Okay, no idea how, but I was able to reproduce, so there's definetly a bug. Will investigate further and fix. I think the mapping is just not working right, like when getting a state update it cannot correlate the right objective/summon... Hopefully an easy fix...

**Comment by sahilthapar** [comment] 2023-05-08 18:15
> There are two "a" and two "b" spawn points but the scenario only adds two monsters. One for "a" and one for "b". It should spawn four monsters instead

Fixing this, it should be one per objective that is still alive.

**Comment by Lurkars** [comment] 2023-05-09 18:04
I forgot the reminder, but otherwise all issues are addressed in [v0.64.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.64.0). I now added unique ids to objectives and summons to identify them on sync. This may lead to migration issues, so maybe running scenarios might run into this issue ONE time again, but afterwards it shouldn't happen. Happy about testing from your side and feedback if it seems solved to you.

**Comment by sahilthapar** [comment] 2023-05-09 19:20
Thanks for the quick turn around. I'll take a backup of the data just in case, we will be playing next over the weekend so will update if there are any issues.

**Comment by sahilthapar** [comment] 2023-05-12 14:41
@Lurkars Is there a way to remove scenarios from the available scenarios list. I can see a way to do that for the random scenarios but 31 got unlocked incorrectly after scenario 20 and I can't find a way to remove it anymore.

**Comment by Lurkars** [comment] 2023-05-13 07:14
Are you on latest version? The wrong unlock from scenario 20 should be fixed, so should be removed automatically.

**Comment by sahilthapar** [comment] 2023-05-15 01:37
Fixed, thanks.

**Comment by sahilthapar** [comment] 2023-06-11 17:07
I saw many issues resurface in our most recent session, Scenario 19. Re-opening this issue and providing some updates:

- Boneshaper and Banner Spear, both are having troubles with duplicate summons being added on client connect / disconnect. This means having to continuously delete summons.
- Objectives in this scenario had similar troubles, especially if we wanted to change their numbers. Ideally, when altar 1 dies it should spawn dark fog 1.

**Comment by Lurkars** [comment] 2023-06-15 07:53
Can you please check if all clients really made it to the latest version and are you using latest server?

**Comment by sahilthapar** [comment] 2023-06-16 15:26
I'll double check all clients during the next session, however I can confirm the server was the latest version as we update and restart our server right before we start the session.

**Comment by Lurkars** [comment] 2023-06-17 05:39
Okay, I got similar reports. Have to check. But it never happens to monsters only summons right?

**Comment by sahilthapar** [comment] 2023-06-17 19:56
Yes, that's correct

**Comment by Lurkars** [comment] 2023-06-21 20:31
I removed old migration now in [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). I hope this will fix all issues.

**Closed** 2023-08-20 21:08 UTC
Labels: bug, to test
