### ISSUE TITLE
Feature Request: Add toggle to prevent negative conditions from expiring

### ISSUE THREAD

**Issue by Solmyr14** [Lurkars/gloomhavensecretariat#355] opened 2023-08-06 05:07 UTC
### Is your feature request related to a problem? Please describe.

The Shackles class has an ability that "During this and the next four rounds, you are unaffected by negative conditions you have, and they cannot be removed". However this is counter to how it normally works so at the end of each turn some conditions will expire (Disarm, Immobilize, etc), or at the beginning of the turn Wound triggers, or being hit triggers certain conditions (Poison, Brittle), or a heal removing conditions heal can remove (Wound, Poison, Brittle, etc) and not healing if there was Poison. So for the duration of the ability, you must keep a close eye on if any negative conditions expire and/or replace lost health from a Wound.

There is actually a perk that does a similar thing but only when Long Resting.

### Describe the solution you'd like

The Fist class has a persistent ability card that refreshes Regen at the start of it's turn and there is a toggle to turn that feature on/off. I realize this is more complicated than that, but could there be a similar toggle to prevent negative conditions from triggering or expiring, or being affected by heals. As well as allowing new negative conditions to be added, but still not triggering or expiring while toggle it on.

### Describe alternatives you've considered

If that is too complicated (or too much work), could there be a way of replacing the actual negative conditions (that have coding behind them) with "fake" negative conditions (just an image, no coding linked the them) while the toggle is on?

### Additional context

I know beginner level coding, so all of this is well beyond my understanding, so I don't know really how difficult this would be to implement. It would just be a very nice to have for those playing Shackles.

Cheers!

**Comment by Lurkars** [comment] 2023-08-06 09:14
What do you think about adding toggles to make a condition persistent and immunity...so you still have to manually enable/disable those special state, but can at least preserve the condition as required by card.

**Comment by Solmyr14** [comment] 2023-08-06 13:34
I think that could work.

Just talking it through. So, when toggled on, a condition would be persistent (can't be removed through normal means) and have immunity (so won't actually affect the character). Also, since it on an individual basis, you can freely add (or remove if required) conditions without affecting the others.

Yeah, I think that could work.

**Comment by Lurkars** [comment] 2023-08-07 17:59
As always, I hope I didn't break anything, because that condition stuff is really a mess :sweat_smile: . So I have now removed the extra permanent condition from the specific classes, instead now there are two toggle on the bottom for setting a condition as permanent and to set an immunity for a condition. What I really wasn't able to test in the short time now is, if immunity is really considered on every condition apply. I tested the obvious one, wound, poison, brittle and regenerate, but it would be really nice if you or someone else can play around with this. In general you should achieve your needs, by setting a condition to permanent and immunity at the same time. 

So checkout [v0.72.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.72.0)

**Comment by Solmyr14** [comment] 2023-08-07 18:06
That's amazing, thank you. I just took a very quick look at it and it seems to work great. Unfortunately due to real world happenings my group and I won't be able to test it for a couple of weeks, but if/when we find any issues, I let you know.

**Comment by mentonin** [comment] 2023-08-28 06:30
1. immunity + permanent poison (or pre applied poison) does not add damage, but cancels heals (and removes pre applied poison). Wound, brittle, bane similarly
2. applying condition > immunity leaves condition applied
3. regen does not heal when immune, but gets removed when damaged
5. applying condition > permanent > !permanent removes condition (opposite from immunity)
6. not related to this feature, but it would be cool to add (optional) confirmation to every condition. Currently, wound, poison, brittle and bane ask for heal confirmation; wound, poison, brittle, bane, ward ask for damage confirmation; brittle + ward and regen do not ask for damage confirmation; turn effects (wound, bane, regen) do not ask for confirmation; shield is not implemented.
7. Also, regen + ward removes regen on 1 dmg that is reduced to 0

**Comment by Lurkars** [comment] 2023-08-28 08:59
1. will be fixed
2. can you provide example? apply dialog should not happened when immune...
3. will be fixed
4. sorry, I don't understand, please give some details
5. I don't want to add dialogs for condition like wound, so I will keep the difference between applicable conditions and conditions that requires confirmation. Anyways, what I already thought of is adding settings to enable/disable those features per condition. So for example, disable automatic apply of regen, but enable for wound, disable dialog for poison but, enable for heal. Also a setting for like applying shield value is a cool idea, but must be disabled by default of course to not confuse current users. I will add this to #160 
6. will be fixed

**Comment by mentonin** [comment] 2023-08-28 14:39
Example for 2 and 3:

Immunity behavior with pre-applied condition:
1. open conditions dialog
2. click on poison
3. click on immunity, then click on poison
4. deselect immunity
5. poison is still circled and one can disable it from base condition menu, but can't re-enable
6. poison still interacts with heals (same bug that permanent conditions have)
7. disabling poison removes condition, not immunity
8. disabling poison immunity leaves condition applied (unless it was cleared, of course)

Permanent condition behavior with pre-applied condition:
1. open conditions dialog
2. click on poison
3. click on permanent, then click on poison
4. deselect permanent
5. poison is still circled and one can disable it from base condition menu
6. disabling poison leaves no condition applied
7. disabling permanent poison leaves no condition applied

I would expect the behavior to be the same on both.

I hope this clears it up.

**Comment by Lurkars** [comment] 2023-08-31 12:34
Okay, this is just bad UX, because the behavior is not the same on purpose.

You can't have non-permanent and permanent condition at once, like the permanent is just toggling permanent of one condition, so for example, you can have wound and then toggle that wound is permanent or not. But it's technically and logical the same condition. So you can deselect, select etc. 

But the immunities are not conditions, but immunites. They just use the same condition interface, but you can have a condition and a immunity of that condition at once (explicit requirement if this issue, with combination of permanent to not automatically remove condition), but you can't have a permanent condition and a non-permanent condition at the same time. If you have wound, you have wound. Permanent just toggles if it is removable automatically (through heal) for example or not. So the expectation is wrong, and that caused by my bad UX, cause the toggles for permanent and immunity appears same, but it's technically and logical a different behaviour. Think of immunities as of immunities on a stat card. That's an immunity, not a condition (while of cause permanent condition is a condition).

**Closed** 2024-01-04 19:31 UTC
Labels: enhancement, to test, spoiler
