### ISSUE TITLE
[FH] Brittle and Ward conditions do not double/halve damage

### ISSUE THREAD

**Issue by ronderksen** [Lurkars/gloomhavensecretariat#285] opened 2023-05-10 07:54 UTC
If my character has the brittle condition and I get 2 or more damage, the app only adds 1 damage for brittle, when it should double the initial damage (so 2 becomes 4, 3 becomes 6, etc.).

Same for the Ward condition, but in the other direction. So 2-3 damage should become 1, 4-5 damage should become 2, etc.

**Comment by Lurkars** [comment] 2023-05-10 09:21
Thanks, I first couldn't reproduce, but then notice, there is a different behavior when dragging HP and dec. HP in menu. Will be fixed. 

While testing I also noticed another issue regarding ward (and maybe other effects?) which I will also address:
I thought it's comfort of not be able to decrease more than max HP, but actually for ward the exact value is important. Current behavior is for example on a max. 4 HP enemy, you can only apply max -4 HP regardless of actual damage, which results in -2 HP with ward. But if you do 6 damage for example, you should be able to apply -6 HP instead and result in -3 HP with ward. Will be fixed today!

**Comment by Lurkars** [comment] 2023-05-10 17:13
Should be fixed in [v0.64.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.64.1). Please verify and close issue if solved.

**Closed** 2023-05-11 13:02 UTC
Labels: bug, to test
