### ISSUE TITLE
Settings disabled after v0.60.0 update (on iOS)

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#240] opened 2023-04-18 02:05 UTC
Sharing my experience after the [v0.60.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.60.0) update in case anything further needed investigating.

When I opened the existing PWA app on iOS (both on iPad and iPhone), I received the game backup prompt, which I closed and then saw this:
![image](https://user-images.githubusercontent.com/124784924/232650368-272441a7-0d11-495e-8748-37bd6220ccf7.png)

I force closed and re-opened the app and it seemed ok, except that all the Settings were deselected requiring them to be reenabled. This more importantly included the 'Additional Gameplay' options like 'Monsters', 'Party Sheet' and the gameplay options like 'Scenario Rooms'., which make it seem like the app is broken or not displaying data.

These were the settings set:

![image](https://user-images.githubusercontent.com/124784924/232650056-f72b8083-701f-4873-a9ff-70b87085cadc.png)
![image](https://user-images.githubusercontent.com/124784924/232650159-b9a56671-8232-4195-994f-75993339570f.png)
![image](https://user-images.githubusercontent.com/124784924/232650207-bec2e5a9-0834-422d-bc4b-58f59cea073b.png)

All the settings seemed to have been restored and work fine on PC (Edge browser)

No other real issues detected.

**Comment by Lurkars** [comment] 2023-04-18 04:51
Do you sync settings with server or did this definitely happen without sync?

**Comment by TheSquinter** [comment] 2023-04-18 05:02
Couldn't be sure - it's not currently ticked to sync settings. I rarely use it on iOS. I just opened it to do a quick test when I saw you mention it was going to trigger a game export. Wanted to see how that looked on iOS devices.

**Comment by TheSquinter** [comment] 2023-04-18 22:29
Sounds good to me

**Comment by Lurkars** [comment] 2023-04-19 11:42
Happened to me now testing on a Firefox Android when upgrading from v0.59.2 to v0.60.2. of course now not directly reproducible, but at least I have a data dump and can try to use a downgraded version and try again to see what happens there. But issue definitely not fixed by now. I now think that those were all settings missing and the prev. version, so upgrading from a v0.59.11 worked, and now from v0.59.2 not. Will check.

**Comment by Lurkars** [comment] 2023-04-19 17:18
Couldn't reproduce on desktop, adjusted now a few other things regarding loading/storing/migrating settings, so hopefully fixed.

**Comment by Lurkars** [comment] 2023-04-23 21:05
Got no more reports about this. If someone still experience the issue, importing the prev. downloaded backup should work to also get settings back.

**Closed by Lurkars** 2023-04-23 21:05 UTC
Labels: bug, to test, in progress
